env:
  global:
    - CC_TEST_REPORTER_ID=b725f47012bc6d1ae59ee6ea725ba55daab2af321daf32210a8fb9d624facd44


language: python
python: "3.5.5"
services:
  - postgresql
addons:
  postgresql: "9.6"

install:
  - export PROJECT_DIR=`pwd`
  - cd /tmp
  - git clone https://github.com/uclouvain/osis-portal.git
  - cd osis-portal
  - git checkout qa
  - git pull origin qa
  - git submodule init
  - git submodule update
  - pip install -r requirements.txt
  - rm -Rf dissertation
  - ln -s $PROJECT_DIR dissertation

before_script:
  - cp .env.example .env
  - echo 'APPS_TO_TEST += ("dissertation",)' >> frontoffice/settings/local.py
  - echo >> .env
  - echo "POSTGRES_USER = 'postgres'" >> .env
  - echo "POSTGRES_PASSWORD = ''" >> .env
  - psql -c 'create database osis_portal_local;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python3 manage.py compilemessages && coverage run manage.py test dissertation --exclude-tag=selenium --no-logs

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

