# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20181203_1026'),
        ('dissertation', '0019_offerproposition_global_email_to_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dissertations', to='base.EducationGroupYear'),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='education_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup'),
        ),
    ]
