# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-09 14:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0021_auto_20190108_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='offer_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
