# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-11 10:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0022_auto_20190109_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(choices=[('UNDEFINED', 'undefined'), ('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], default='UNDEFINED', max_length=12, null=True, verbose_name='Defend period'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defend year'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.DissertationLocation', verbose_name='Dissertation location'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation', verbose_name='Dissertation subject'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Dissertation'),
        ),
        migrations.AlterField(
            model_name='dissertationrole',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser', verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='level',
            field=models.CharField(choices=[('SPECIFIC', 'specific subject'), ('THEME', 'large theme')], default='DOMAIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='type',
            field=models.CharField(choices=[('RDL', 'litterature review'), ('EMP', 'empirical research'), ('THE', 'theoretical analysis'), ('PRO', 'project dissertation'), ('DEV', 'Development dissertation'), ('OTH', 'other')], default='RDL', max_length=12),
        ),
    ]
