# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-13 08:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0024_auto_20190213_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertationupdate',
            name='dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='dissertation_updates',
                                    to='dissertation.Dissertation'),
        ),
    ]
