# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-24 08:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0025_auto_20190313_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dissertation.DissertationLocation', verbose_name='Dissertation location'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='offer_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.OfferYear'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dissertations', to='dissertation.PropositionDissertation', verbose_name='Dissertation subject'),
        ),
        migrations.AlterField(
            model_name='dissertationrole',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dissertation.Adviser', verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='dissertationrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'Promoter'), ('CO_PROMOTEUR', 'Co-Promoter'), ('READER', 'Reader'), ('ACCOMPANIST', 'Accompanist'), ('INTERNSHIP', 'Internship'), ('PRESIDENT', 'President')], max_length=12),
        ),
        migrations.AlterField(
            model_name='dissertationupdate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dissertation.Adviser'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='propositionrole',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dissertation.Adviser'),
        ),
        migrations.AlterField(
            model_name='propositionrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'Promoter'), ('CO_PROMOTEUR', 'Co-Promoter'), ('READER', 'Reader'), ('ACCOMPANIST', 'Accompanist'), ('INTERNSHIP', 'Internship'), ('PRESIDENT', 'President')], default='PROMOTEUR', max_length=12),
        ),
    ]
