# Generated by Django 2.2.5 on 2019-12-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0027_auto_20190919_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dissertation',
            old_name='education_group_year_start',
            new_name='education_group_year',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='offer_year_start',
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'undefined'), ('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], default='UNDEFINED', max_length=12, null=True, verbose_name='Defense period'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defense year'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
